# Generated by Django 5.2.4 on 2025-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('detailed_description', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('readme_sync_enabled', models.BooleanField(default=False)),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_thumbnails/')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
