# Generated by Django 5.2.4 on 2025-07-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('website_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ranking', models.CharField(blank=True, max_length=50)),
                ('contests_participated', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(blank=True, max_length=100)),
                ('last_error', models.TextField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='coding.codingplatform')),
            ],
            options={
                'unique_together': {('platform', 'username')},
            },
        ),
    ]
