# Generated by Django 5.2.4 on 2025-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofile',
            name='easy_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingprofile',
            name='hard_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingprofile',
            name='medium_solved',
            field=models.IntegerField(default=0),
        ),
    ]
