# Generated by Django 5.2.4 on 2025-07-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_codingprofile_easy_solved_codingprofile_hard_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofile',
            name='easy_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingprofile',
            name='hard_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingprofile',
            name='medium_total',
            field=models.IntegerField(default=0),
        ),
    ]
